# Generated by Django 3.0.3 on 2020-03-11 09:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualLocalization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('pred_country', models.CharField(max_length=100, null=True)),
                ('true_country', models.CharField(max_length=100, null=True)),
                ('correct', models.NullBooleanField()),
            ],
        ),
    ]
