# Generated by Django 3.0.3 on 2020-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VL', '0002_auto_20200312_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visuallocalization',
            name='pred_country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visuallocalization',
            name='true_country',
            field=models.CharField(choices=[('0', '호주'), ('1', '한국'), ('2', '프랑스'), ('3', '이탈리아'), ('4', '미국'), ('5', '나도 몰라')], max_length=20, null=True),
        ),
    ]
