# Generated by Django 3.0.3 on 2020-03-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VL', '0005_auto_20200314_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visuallocalization',
            name='true_country',
            field=models.CharField(blank=True, choices=[('0', '호주'), ('1', '프랑스'), ('2', '이탈리아'), ('3', '한국'), ('4', '미국')], max_length=20),
        ),
    ]
